plugins {
    id 'com.android.application' version '9.0.1'
}
android {
    namespace 'com.ninebot.hook'
    compileSdk 34
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    defaultConfig {
        applicationId "com.ninebot.hook"
        minSdk 24
        targetSdk 34
        versionCode 3
        versionName "0.36"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }
}
repositories {
    google()
    mavenCentral()
    maven { url "https://api.xposed.info/" }
}
dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
    compileOnly fileTree(dir: 'libs', include: ['*.jar'])
}
