android.useAndroidX=true
# 允许项目路径含中文
android.overridePathCheck=true
android.suppressExperimentalOptionWarnings=true
# 抑制 Java 8 过时警告
android.javaCompile.suppressSourceTargetDeprecationWarning=true
org.gradle.jvmArgs=-Xmx1536m
#禁用部署优化
android.enableInstantRun=false
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false